import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: "10%",
    backgroundColor: "#faf9f4",
  },
  fileIcon: {
    width: 22,
    height: 22,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  sub: {
    flexDirection: "row",
    alignItems: "center",
  },
  title: {
    fontFamily: "inter-bold",
    fontSize: 28,
    marginLeft: 12,
  },
  tripContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#D3D3D3",
  },
  tripLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  avatar: {
    height: 48,
    width: 48,
    borderRadius: 24,
    marginRight: 12,
  },
  locationText: {
    flexDirection: "column",
  },
  fromText: {
    fontFamily: "inter-medium",
    fontSize: 22,
    color: "#444",
  },
  bold: {
    fontFamily: "inter-semibold",
    color: "#000",
  },
  optionBox: {
    position: "absolute",
    top: 70,
    right: 16,
    backgroundColor: "white",
    borderRadius: 12,
    shadowColor: "#000",
    shadowRadius: 4,
    elevation: 5,
    width: 180,
    zIndex: 10,
  },
  item: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#D3D3D3",
  },
  text: {
    marginLeft: 12,
    fontSize: 16,
    color: "#111",
    fontFamily: "inter-medium",
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 10,
    paddingVertical: 5,
    margin: 12,
    borderRadius: 10,
    marginBottom: 40,
  },
  textInput: {
    flex: 1,
    fontSize: 16,
    fontFamily: "inter-regular",
    color: "#000",
  },
  iconButton: {
    marginLeft: 12,
  },
  btnBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    backgroundColor: "#008000",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 40,
    position: "absolute",
    bottom: 100,
    right: 30,
    zIndex: 20,
  },
  btniItem: {
    padding: 10,
    paddingVertical: 5,
  },
  avatarWrapper: {
    position: "relative",
    marginHorizontal: 8,
    marginTop: 4,
  },
  dpImage: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  verifiedIcon: {
    position: "absolute",
    bottom: -2,
    right: -2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "#fff",
  },
  receiverShadow: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
    backgroundColor: "#fff",
  },
  dropdownWrapper: {
    position: "absolute",
    right: 1,
    top: 100,
    zIndex: 100,
  },
});
